Controllers/LeagueController.cs
using FootballManager_SoftuniProject.Core.Contracts.League;
using FootballManager_SoftuniProject.Core.Models.League;
using FootballManager_SoftuniProject.Core.Services.Manager;
using FootballManager_SoftuniProject.Data;
using FootballManager_SoftuniProject.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FootballManager_SoftuniProject.Controllers
{
    public class LeagueController : Controller
    {
        private readonly ILeagueService leagueService;

        public LeagueController(ILeagueService _leagueService)
        {
            leagueService = _leagueService;
        }

        public async Task<IActionResult> ChooseLeague()
        {
            if (await leagueService.ExistsById(User.Id()))
            {
                return RedirectToAction("ProfileDetails", "Profile");
            }

            var model = await leagueService.AllLeagues();

            return View(model);
        }
    }
}

Controllers/StadiumController.cs
using FootballManager_SoftuniProject.Core.Models.League;
using FootballManager_SoftuniProject.Core.Models.Player;
using FootballManager_SoftuniProject.Core.Models.Stadium;
using FootballManager_SoftuniProject.Core.Models.Team;
using FootballManager_SoftuniProject.Data;
using FootballManager_SoftuniProject.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace FootballManager_SoftuniProject.Controllers
{
    public class StadiumController : Controller
    {
        private readonly FootballManagerDbContext context;

        public StadiumController(FootballManagerDbContext _context)
        {
            context = _context;
        }

        [HttpGet]
        public async Task<IActionResult> AllStadiums()
        {
            var model = await context.Stadiums
                .AsNoTracking()
                .Select(p => new AllStadiumViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                })
                .ToListAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddStadiums()
        {
            var stadium = new AllStadiumViewModel();

            return View(stadium);
        }

        [HttpPost]
        public async Task<IActionResult> AddStadiums(AllStadiumViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new ArgumentException("Error with Add Stadium Action");
            }

            var stadium = new Stadium()
            {
                Name = model.Name,
            };

            await context.Stadiums.AddAsync(stadium);
            await context.SaveChangesAsync();

            return RedirectToAction(nameof(AllStadiums));
        }
    }
}

Controllers/TeamController.cs
using FootballManager_SoftuniProject.Core.Contracts.Team;
using FootballManager_SoftuniProject.Core.Models.League;
using FootballManager_SoftuniProject.Core.Models.Team;
using FootballManager_SoftuniProject.Data;
using FootballManager_SoftuniProject.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace FootballManager_SoftuniProject.Controllers
{
    public class TeamController : Controller
    {
        public readonly FootballManagerDbContext context;

        public TeamController(FootballManagerDbContext _context)
        {
            context = _context;
        }

        public async Task<IActionResult> ChooseTeam()
        {
            var model = await context.Teams
                .AsNoTracking()
                .Where(t => t.UserId == GetUserId())
                .Select(t => new AllTeamsViewModels()
                {
                    Id = t.Id,
                    Name = t.Name,
                    ImageUrl = t.ImageUrl
                })
                .ToListAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddTeam(int id)
        {
            var team = new AddTeamViewModel();

            team.League = await context.League
                .AsNoTracking()
                .Select(s => new AllLeaguesViewModel()
                {
                    Id = s.Id,
                    Name = s.Name
                })
                .ToListAsync();

            return View(team);
        }

        [HttpPost]
        public async Task<IActionResult> AddTeam(AddTeamViewModel model, int id)
        {
            var checkTeam = await context.Teams.FirstOrDefaultAsync(t => t.Name == model.Name);

            if (checkTeam != null)
            {
                throw new ArgumentException("Sry the team already exist");
            }

            if (!ModelState.IsValid)
            {
                throw new ArgumentException("Error with Add Action");
            }

            var team = new Team()
            {
                Name = model.Name,
                Country = model.Country,
                ImageUrl = model.ImageUrl,
                StadiumId = id,
                LeagueId = model.LeagueId,
                UserId = GetUserId()
            };

            await context.Teams.AddAsync(team);
            await context.SaveChangesAsync();

            return RedirectToAction(nameof(ChooseTeam));
        }

        private string GetUserId()
        {
            return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
        }
    }
}

Views/League/ChooseLeague.cshtml
@model IEnumerable<AllLeaguesViewModel>
@{
    ViewBag.Title = "Please choose a league";
    string[] leagues = new[] { "Premier League", "LaLiga" };
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="text-center row">
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        @foreach (var l in Model.Where(l=>l.Name == "Admin"))
        {
                    <div class="card col-4" style="width: 20rem; ">
                                    <div class="card-body">
                                        <h4 class="card-title mt-1">@l.Name</h4>
                                            <img class="d-block w-100" style="height:300px" src="@l.ImageUrl">
                                    </div>
                                            <a asp-controller="Team" asp-action="ChooseTeam" class="btn btn-success mb-2 w-100 p-3 fw-bold">Choose a Team</a>
                                                    <a asp-controller="Stadium" asp-action="AddStadiums" asp-route-id="@l.Id" class="btn btn-success mb-2 w-100 p-3 fw-bold">Choose a Stadium</a>
                                </div>

        }
    }
    else
    {
        @foreach (var l in Model.Where(l=>l.Id != 1))
        {
                    <div class="card col-4" style="width: 20rem; ">
                                    <div class="card-body">
                                        <h4 class="card-title mt-1">@l.Name</h4>
                                            <img class="d-block w-100" style="height:300px" src="@l.ImageUrl">
                                    </div>
                                            <a asp-controller="Stadium" asp-action="AllStadiums" class="btn btn-success mb-2 w-100 p-3 fw-bold">Choose</a>
                                </div>

        }
    }

</div>

@section Scripts {
        <partial name="_ValidationScriptsPartial" />
}